In [3]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/alcohol-consumption/drinks.csv")
df

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,Afghanistan,0,0,0,0.0
1,Albania,89,132,54,4.9
2,Algeria,25,0,14,0.7
3,Andorra,245,138,312,12.4
4,Angola,217,57,45,5.9
...,...,...,...,...,...
188,Venezuela,333,100,3,7.7
189,Vietnam,111,2,1,2.0
190,Yemen,6,0,0,0.1
191,Zambia,32,19,4,2.5
192,Zimbabwe,64,18,4,4.7

In [8]:
import pandas as pd
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

df

numero_offerte_per_paese=df.groupby("job_country").count()
numero_offerte_per_paese

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_country,,,,,,,,,,,,,,,,
Afghanistan,16,16,16,16,14,16,16,16,16,16,0,0,0,16,12,12
Albania,119,119,119,119,116,119,119,119,119,119,5,5,0,119,108,108
Algeria,111,111,111,111,111,111,111,111,111,111,4,2,2,111,75,75
Angola,11,11,11,11,11,11,11,11,11,11,0,0,0,11,8,8
Argentina,8736,8736,8736,8736,8719,8736,8736,8736,8736,8736,33,32,1,8736,7509,7509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,69,69,69,69,69,69,69,69,69,69,2,0,2,69,54,54
Vietnam,2414,2414,2414,2414,2412,2414,2414,2414,2414,2414,74,55,0,2414,1981,1981
Yemen,10,10,10,10,9,10,10,10,10,10,0,0,0,10,7,7
Zambia,104,104,104,104,103,104,104,104,104,104,1,1,0,104,74,74
Zimbabwe,81,81,81,81,79,81,81,81,81,81,4,3,1,81,45,45